
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    username: root
    password: root3it
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
